name: Build Ardour

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        libboost-all-dev gcc g++ pkg-config libasound2-dev libgtk2.0-dev \
        libsndfile1-dev libcurl4-nss-dev libarchive-dev liblo-dev libtag1-dev \
        vamp-plugin-sdk librubberband-dev libfftw3-dev libaubio-dev libxml2-dev \
        lv2-dev libserd-dev libsord-dev libsratom-dev liblilv-dev libgtkmm-2.4-dev \
        libglibmm-2.4-dev libusb-1.0-0-dev libpangomm-1.4-dev libsamplerate0-dev \
        libcunit1-dev libcppunit-dev libudev-dev libserd-0-0 libcwiid-dev \
        libxwiimote-dev libwebsocketpp-dev libwebsockets-dev \
        libsratom-0-0 liblrdf0 liblrdf0-dev libsuil-dev

    - name: Build Ardour
      run: |
        cd ardour
        ./waf configure
        ./waf
